version = 1

test_patterns = ["src/**/*.ts", tsconfig.json]

exclude_patterns = ["src/**/*.test.ts", "examples/**", "scripts/**", "jest.setup.ts"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser"]
  dialect = "typescript"
